### ISSUE TITLE
Change name that appears in Fedora Sound Panel

### ISSUE THREAD

**Issue by djg** [djg/audioipc-2#20]
Firefox appears as AudioIPC Server. We should change that.

![audioipc](https://user-images.githubusercontent.com/156077/32358069-59e92bd6-c08e-11e7-9d8a-02577b15a34f.png)

**Comment by kinetiknz** [comment]
This is because the cubeb context string isn't plumbed through.  We do some work in [CubebUtils](https://hg.mozilla.org/mozilla-central/file/tip/dom/media/CubebUtils.cpp#l402) to generate a suitable string from the brand name, but on the client context completely ignores it and it's not passed to the server at all.

**Comment by kinetiknz** [comment]
Fixed via https://github.com/djg/audioipc-2/pull/66
