### ISSUE TITLE
Input buffer is not null in output only callback

### ISSUE THREAD

**Issue by achronop** [djg/audioipc-2#42]
In output only callback the input buffer expected to be null which is not the case in remote case (haven't tested the non remote case).

https://github.com/djg/audioipc-2/blob/219a811b62b83bd6e4cb54ae6aebc56bbb43203c/client/src/stream.rs#L101

**Comment by kinetiknz** [comment]
PR #44 fixes the immediate issue.

I think we should also avoid setting up the shared memory for stream directions that are unused, since it's a waste of resources.  I tried doing this initially, but it's a bit of a pain as the IPC is hardcoded to expect 3 FDs for control/input/output, so I decided to fix the client for now and address the rest as an optimization in another bug.

**Comment by kinetiknz** [comment]
I guess this can be closed, since this is fixed and the improvements are tracked in #45.
